### ISSUE TITLE
Atheros Lan card

### ISSUE THREAD

**Issue by piik9** [fbelavenuto/arpl-addons#10]
Can you add Atheros AR816x/AR817x drivers?
https://github.com/pocopico/rp-ext/tree/main/alx

**Comment by fbelavenuto** [comment]
Added:

https://github.com/fbelavenuto/arpl-addons/releases/tag/v1.4

Please update addons from loader menu.

**Comment by piik9** [comment]
Thanks

**Comment by piik9** [comment]
Thanks
