### ISSUE TITLE
can you add 10th, 11th, 12th cpu igpu support driver?

### ISSUE THREAD

**Issue by green1052** [fbelavenuto/arpl-addons#13]
https://xpenology.com/forum/topic/59909-i915ko-backported-driver-for-intel-10th-gen-ds918-ver-701-up3/

**Comment by fbelavenuto** [comment]
Added into last addons, please update addons, add addon and rebuild

**Comment by green1052** [comment]
thx i will try

**Comment by green1052** [comment]
it's support ds3622xs+?

**Comment by green1052** [comment]
and how to add addons?
for User addons tab?

**Comment by fbelavenuto** [comment]
Nop, only apollolake (DS918+) and geminilake (DS920+, DVA1622). I don't have equipment to test, I'm relying on forum reports.

With the correct model selected and the build selected, go to the addons menu, the i915 addon will appear for selection.

**Comment by green1052** [comment]
i gonna try 918+

**Comment by green1052** [comment]
not working 918

![image](https://user-images.githubusercontent.com/34261355/183702358-9f192419-17db-4625-9bc2-339398bb29e8.png)

**Comment by green1052** [comment]
smae 920+ 

i am using g6900

**Comment by fbelavenuto** [comment]
Check if module has loaded. Type: 
**lsmod | grep i915**

**Comment by green1052** [comment]
![image](https://user-images.githubusercontent.com/34261355/183710488-6db4b9d3-0da6-4d29-8cf6-fd2f911e9469.png)

i disable vt-d, vt

**Comment by Cryental** [comment]
Check your cpu igpu model id, and tell us.

**Comment by green1052** [comment]
uhd 710

https://www.intel.co.kr/content/www/kr/ko/products/sku/96163/intel-celeron-processor-g6900-4m-cache-3-40-ghz/specifications.html

**Comment by green1052** [comment]
@Cryental

**Comment by Cryental** [comment]
@fbelavenuto you have to add support for 0x4693

**Comment by r0bb10** [comment]
> uhd 710
> 
> https://www.intel.co.kr/content/www/kr/ko/products/sku/96163/intel-celeron-processor-g6900-4m-cache-3-40-ghz/specifications.html

that is an AlderLake 12th gen cpu, that igpu wont work on kernel 4.4 from synology, blame them, nothing to do until "maybe" kernel 5.10 lands.

sorry

**Comment by fbelavenuto** [comment]
Thanks, if exists another trouble, please open a new issue
