### ISSUE TITLE
i915 extension doesn't support i5-9400

### ISSUE THREAD

**Issue by Cryental** [fbelavenuto/arpl-addons#37]
Hello.

It seems i915 extension doesn't recognize i5-9400's internal graphics card. Device ID is 0x3E98. Can you please add a support for it? Thank you!

**Comment by Cryental** [comment]
If you need to install the i915 for 8-9th gen, please use this link to add the addon:

https://github.com/Cryental/arpl-i915-3e98/releases/download/1.0/i915-3e98.addon

@fbelavenuto also you can try to add this to this repo if you can :)

https://github.com/Cryental/arpl-i915-3e98

**Comment by fbelavenuto** [comment]
> If you need to install the i915 for 8-9th gen, please use this link to add the addon:
> 
> https://github.com/Cryental/arpl-i915-3e98/releases/download/1.0/i915-3e98.addon
> 
> @fbelavenuto also you can try to add this to this repo if you can :)
> 
> https://github.com/Cryental/arpl-i915-3e98

Thanks @Cryental

**Comment by Cryental** [comment]
Thank you for adding 👍🏻 Closing this issue since it's solved!
