### ISSUE TITLE
WOL addon

### ISSUE THREAD

**Issue by spammoogle** [fbelavenuto/arpl-addons#90]
Good morning,
First of all congratulations for his work.

I have installed a DS920+ successfully but "WOL" does not work. From windows it works.

I understand that it does not force the card to be in "g" mode

I am trying to update addons from the ARPL menu but the "WOL" addon does not appear

I tried Download an external addon... but I don't know what url I have to put.

https://github.com/fbelavenuto/arpl-addons/releases/download/v2.47/addons.zip
https://github.com/fbelavenuto/arpl-addons/archive/refs/tags/v2.47.tar.gz
https://github.com/fbelavenuto/arpl-addons/archive/refs/tags/v2.47.zip

All response File format not recognized !

you could help me Thank you.

**Comment by fbelavenuto** [comment]
Hi, this addon is a system addon, it is added automatically.
Do you change the MAC address of your card (via cmdline menu)?

**Comment by spammoogle** [comment]
Ops. ARPL puts a random MAC ?

Under windows. The network card behaves perfectly and I get up with WOL.

I check on Synology WOL option. But the machine does not lift.

I have verified that when I check eth0_wol = "g". But it does not work.

Could it be because of the Asus Motherboard model?

Thank you so much.

**Comment by spammoogle** [comment]
Hi, 
WOL is working... ;-), indeed the MAC was simulated
